### PR TITLE
Bring links up to date

### PR DESCRIPTION
**Pull request by ScottyPoi**
Replace "projects" section of `index.md` with markdown from the monorepo README that has up to date links and package list.

If the team decides to maintain this site, more intention could be put into the design and content, but this at least fixes this issue of deprecated links.

### CODE REVIEW

**Review by acolytec3 — CHANGES_REQUESTED** [review]
At a minimum, we should also update line 234 to reflect the renamed `@ethereum/tx` library name though I would recommend just removing this entire section since we don't really support `keythereum` or `ethereumjs-wallet` anymore.  People should use `ethers` for managing keys/wallets.

**Comment by holgerd77** [comment]
@acolytec3 EthereumJS Wallet has > 130.000 [weekly downloads](https://www.npmjs.com/package/ethereumjs-wallet), let's please not make deprecation decisions on such libraries here so much on the sideline. 😋

**Comment by acolytec3** [comment]
> @acolytec3 EthereumJS Wallet has > 130.000 [weekly downloads](https://www.npmjs.com/package/ethereumjs-wallet), let's please not make deprecation decisions on such libraries here so much on the sideline

Could we deprecate in favor of @paulmillr's micro-eth-signer? Otherwise, shouldn't we pull it into the monorepo and actively maintain it?

**Comment by holgerd77** [comment]
> > @acolytec3 EthereumJS Wallet has > 130.000 [weekly downloads](https://www.npmjs.com/package/ethereumjs-wallet), let's please not make deprecation decisions on such libraries here so much on the sideline
> 
> Could we deprecate in favor of @paulmillr's micro-eth-signer? Otherwise, shouldn't we pull it into the monorepo and actively maintain it?

Again, "500.000 Downloads/months library deprecation decisions" are really not such an easy take (this *was* in discussion a couple of times during the last 2-3 years). E.g. Metamask (yes (!)) is using this wallet.

I don't see the necessity to move to monorepo TBH, this has no interdependencies to other libs. So, the current state is: this is one of our maintained (or: should be maintained) libraries.

**Comment by paulmillr** [comment]
@holgerd77 want me to take a look at upgrading ethereumjs-wallet to latest ethereum-cryptography?

**Comment by holgerd77** [comment]
> @holgerd77 want me to take a look at upgrading ethereumjs-wallet to latest ethereum-cryptography?

Oh, that would be nice, yes! 👍

**Comment by paulmillr** [comment]
https://github.com/ethereumjs/ethereumjs-wallet/pull/172, https://github.com/ethereumjs/keythereum/pull/93

**Pull request closed without merging**
