### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by holgerd77**
Adresses #3

### CODE REVIEW

**Comment by holgerd77** [comment]
Ok, this is now ready. Since this is awful to review by code, I did a little fork deployment at https://holgerd77.github.io/ethereumjs.github.io/.

Only working half though, since reading metadata from this context is not working properly. Nevertheless, should give an impression.

Properly deployed site should look a bit like:

bildschirmfoto 2018-01-24 um 13 15 25

All projects now use the metadata description from GitHub and there is a single ``repository.html`` template we can easily expand from later (I couldn't e.g. include the latest release version number - which I originally wanted to do - since this was more complex than I thought).

I also removed outdated repositories, brought some structure to everything and updated the texts.

**Comment by axic** [comment]
Looks nice!

But I think the grouping is really bad. Please keep a note of the grouping in the old version.

For example:
- `ethereumjs-account` has nothing to do with key management, it is a blockchain related repo
- `ethereumjs-wallet` and `keythereum` are the only real key management ones, but I'd put `helpeth` there too
- `abi` and `tx` should really not have much to do with `blockchain` and `block`
- `wallet`/`units`/`icap` do not have anything in common with mining
- `ethrpc` shouldn't be next to devp2p
- `common` isn't really a useful utility, it is internal to the vm/blockchain

Some proposed categories:
- Key management (wallet, keyethereum, icap, helpeth)
- Dapp development (ethrpc, util, units, abi, tx)
- VM
- devp2p / node

**Comment by holgerd77** [comment]
Ok. Will give it another try. :-)

**Comment by axic** [comment]
Do you want to pull out the other commits (apart from the last two) and merge those right now? (Those only do reorganisations and build improvements).

**Comment by holgerd77** [comment]
Hmm, I didn't commit in chronological work order, this most-for-sure won't work. I'll try another reorg and squash the commit.

**Comment by holgerd77** [comment]
Ok, done, went pretty much along the lines you suggested.

**Comment by holgerd77** [comment]
Is this mergeable now? 

I think this should make more sense now and we won't find a perfect taxonomy anyway. This is just for giving people some basic orientation when they are looking for stuff.

**Comment by holgerd77** [comment]
(I also didn't remove any old grouping, there actually wasn't any except from a alphabetical list: https://ethereumjs.github.io/)

**Comment by holgerd77** [comment]
@axic Is this stuck due to you being not satisfied with sorting this into some kind of categories or just for no-time-to-review reasons?

**Comment by axic** [comment]
No time, should have time this week.

**Comment by holgerd77** [comment]
Can this be merged at some point? It's a bit unsatisfying to get stuck with this super-outdated website while this is in the pipeline.

Should also rather be a starting then an endpoint, since people can now easier/directly update the website with simple PRs, so we can slowly evolve and (hopefully) get this updated/enhanced a bit more frequently.

**Comment by holgerd77** [comment]
Hi @axic, can you do a short other look at the new groupings here? Really just a few lines in ``index.md`` to review. 😄

**Pull request merged**
